project_name: aichat


before:
  hooks:
    - go mod tidy


builds:
  - id: aichat
    binary: aichat
    main: ./cmd/aichat

    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/lenye/aichat/pkg/version.AppName={{.ProjectName}}
      - -X github.com/lenye/aichat/pkg/version.Version={{.Version}}
      - -X github.com/lenye/aichat/pkg/version.BuildCommit={{.ShortCommit}}
      - -X github.com/lenye/aichat/pkg/version.BuildTime={{.CommitDate}}
      - -extldflags
      - -static
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
      - 386
      - arm
      - riscv64
    goarm:
      - 7
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: openbsd
        goarch: arm
        goarm: 6
    mod_timestamp: '{{ .CommitTimestamp }}'


archives:
  - id: aichat
    builds:
      - aichat
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
      - README.md


checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_sha256_checksums.txt"
  algorithm: sha256


changelog:
  filters:
    exclude:
      - '^wip:'
      - '^docs:'
      - '^test:'
      - '^style:'
      - '^chore:'
      - '^ci:'


dockers:
  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-x86_64"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-x86_64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-armv7"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-armv7"
    use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"


docker_manifests:
  - name_template: ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-x86_64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-arm64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-armv7
  - name_template: ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-x86_64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-arm64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-armv7
  - name_template: ghcr.io/lenye/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-x86_64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-arm64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-armv7